Switch to erlef/setup-beam@v1
The actions/setup-elixir repository is no longer maintained

> Please note: This repository is currently unmaintained by a team of developers at GitHub. It is now maintained by the Erlang Ecosystem Foundation at erlef/setup-elixir. Rather than using actions/setup-elixir, please begin referring to that action in your workflows, instead.

Hopefully this will solve the error that many of the runs are encountering:
https://github.com/asummers/plts/runs/2662763314?check_suite_focus=true
> Error: The process '/home/runner/work/_actions/actions/setup-elixir/v1/dist/install-otp' failed with exit code 8